name: Updater (WIP)

on:
  schedule:
    - cron: 0 0 * * 0

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          feed-url: https://wowchemy.com/blog/index.xml
          readme-section: news
